name: pointfree
description: A GUI interface to the Lambda Cloud API and the Lambda Inference API.
repository: https://github.com/lambdal/lambda-cloud-dart-gui
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  openapi:
    path: api

  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  flutter_client_sse: ^2.0.3
  flutter_markdown: ^0.7.5
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  openapi_generator_annotations: ^6.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  openapi_generator: ^6.1.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
    - family: Berkeley Mono
      fonts:
        - asset: assets/fonts/BerkeleyMonoVariable-Regular.ttf
