name: lambda_gui
description: A GUI interface to Lambda Cloud.
repository: https://github.com/lambdal/lambda-cloud-dart-gui
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  openapi:
    path: api

  args: ^2.6.0
  cupertino_icons: ^1.0.8
  openapi_generator_annotations: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  openapi_generator: ^6.1.0
  test: ^1.24.0

flutter:
  uses-material-design: true
